import { DOCUMENT } from '@angular/common';
import {
  Injectable,
  Renderer2,
  RendererFactory2,
  inject,
} from '@angular/core';
import { Meta, Title } from '@angular/platform-browser';

export const SITE_BASE_URL = 'https://doublelonglap.com';
export const SITE_NAME = 'Double Long Lap';
const TITLE_TEMPLATE = '%s · Double Long Lap';
const DEFAULT_TITLE = 'Double Long Lap — MotoAmerica fan hub';
const DEFAULT_DESCRIPTION =
  'Standings, schedule, results, rider profiles, venue guides, and stats for MotoAmerica fans.';
// Single fallback OG image generated by scripts/build-og.ts and copied into
// the build via public/. Per-route satori-style generation is deferred per
// migration plan §3 / decision #2.
const DEFAULT_OG_IMAGE = '/og-default.png';
const JSON_LD_ATTR = 'data-dll-jsonld';

export type SeoOptions = {
  // Page title. If `template` is true, the value is interpolated into
  // "%s · Double Long Lap"; if false, it's used verbatim. Default: true.
  title: string;
  template?: boolean;
  description?: string;
  // Path or absolute URL. Resolved against SITE_BASE_URL when relative.
  canonical?: string;
  ogImage?: string;
};

@Injectable({ providedIn: 'root' })
export class SeoService {
  private readonly title = inject(Title);
  private readonly meta = inject(Meta);
  private readonly doc = inject(DOCUMENT);
  private readonly renderer: Renderer2;

  constructor() {
    // RendererFactory2 lets us mutate the DOM in a way that works under SSR
    // (where direct document mutation is fine) and the browser. Required for
    // injecting <script> elements that Angular's template compiler otherwise
    // strips for security.
    this.renderer = inject(RendererFactory2).createRenderer(null, null);
  }

  setMeta(opts: SeoOptions): void {
    const fullTitle = opts.template === false ? opts.title : TITLE_TEMPLATE.replace('%s', opts.title);
    const description = opts.description ?? DEFAULT_DESCRIPTION;
    const url = this.resolveUrl(opts.canonical);
    const ogImage = this.resolveUrl(opts.ogImage ?? DEFAULT_OG_IMAGE);

    this.title.setTitle(fullTitle);
    this.meta.updateTag({ name: 'description', content: description });
    this.meta.updateTag({ property: 'og:site_name', content: SITE_NAME });
    this.meta.updateTag({ property: 'og:type', content: 'website' });
    this.meta.updateTag({ property: 'og:locale', content: 'en_US' });
    this.meta.updateTag({ property: 'og:title', content: fullTitle });
    this.meta.updateTag({ property: 'og:description', content: description });
    if (url) this.meta.updateTag({ property: 'og:url', content: url });
    if (ogImage) this.meta.updateTag({ property: 'og:image', content: ogImage });
    this.meta.updateTag({ name: 'twitter:card', content: 'summary_large_image' });
    if (url) this.setCanonical(url);
  }

  // Idempotently inserts (or replaces) a JSON-LD <script> in <head>. Multiple
  // payloads on the same page can coexist by using different `slot` keys
  // (e.g. 'site', 'breadcrumb', 'event'); each slot owns one script element.
  setJsonLd(
    data: Record<string, unknown> | Array<Record<string, unknown>>,
    slot: string = 'default',
  ): void {
    const head = this.doc.head;
    const selector = `script[${JSON_LD_ATTR}="${slot}"]`;
    let script = head.querySelector<HTMLScriptElement>(selector);
    if (!script) {
      script = this.renderer.createElement('script') as HTMLScriptElement;
      script.type = 'application/ld+json';
      script.setAttribute(JSON_LD_ATTR, slot);
      this.renderer.appendChild(head, script);
    }
    script.textContent = JSON.stringify(data);
  }

  resetToDefaults(): void {
    this.setMeta({
      title: DEFAULT_TITLE,
      template: false,
      description: DEFAULT_DESCRIPTION,
      canonical: '/',
    });
  }

  private resolveUrl(value: string | undefined): string | undefined {
    if (!value) return undefined;
    if (value.startsWith('http://') || value.startsWith('https://')) return value;
    const path = value.startsWith('/') ? value : `/${value}`;
    return `${SITE_BASE_URL}${path}`;
  }

  private setCanonical(url: string): void {
    const head = this.doc.head;
    let link = head.querySelector<HTMLLinkElement>('link[rel="canonical"]');
    if (!link) {
      link = this.renderer.createElement('link') as HTMLLinkElement;
      link.setAttribute('rel', 'canonical');
      this.renderer.appendChild(head, link);
    }
    link.setAttribute('href', url);
  }
}
